#!/bin/sh
/usr/local/lib/node_modules/typescript/bin/tsc --version
/usr/local/lib/node_modules/typescript/bin/tsc --rootDir source/ --outDir dist/  source/*.ts source/host/*.ts source/os/*.ts
echo Operating System has finsihed compiling at $(date)
